version: '3.8'

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16  # avoid 192.168.x.x

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: BackendSpeed/Dockerfile.backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_POSTGRESQL_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}    # for Flyway
      OPENAPI_SPEC_PATH: /app/api.yaml
      APP_WANIKANI_USE_DEV_CACHE: "true"
    depends_on:
      - db
      - python_dict
    ports:
      - "8080:8080"
    volumes:
      - ./api.yaml:/app/api.yaml
      - ./JMdict_e.xml:/app/jmdict_e.xml
      - ./anki/collection.db:/app/anki/collection.db
      - ./htmlImports:/app/htmlImports:ro

  frontend:
    build:
      context: .
      dockerfile: FrontendQuiz/Dockerfile.frontend
    ports:
      - "4200:80"
    volumes:
      - ./api.yaml:/app/api.yaml

  nginx:
    build:
      context: .
      dockerfile: FrontendQuiz/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./KanjiVG:/usr/share/nginx/html/kanjivg:ro

  python_dict:
    build:
      context: .
      dockerfile: PythonDict/Dockerfile.python_dict
    ports:
      - "8000:8000"

volumes:
  db-data:
