# PostgreSQL
spring.datasource.postgresql.url=jdbc:postgresql://db:5432/speedquizdb

# Flyway
spring.flyway.url=jdbc:postgresql://db:5432/speedquizdb

# SQLite (read-only Anki data)
spring.datasource.sqlite.url=jdbc:sqlite:/app/anki/collection.db
spring.datasource.sqlite.driverClassName=org.sqlite.JDBC

# App-specific overrides
app.deck-import.path=./htmlImports