spring.application.name=BackendSpeed
# PostgreSQL datasource configuration
spring.datasource.url=jdbc:postgresql://db:5432/speedquizdb
spring.datasource.username=speedquiz
spring.datasource.password=changeMe
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.url=jdbc:postgresql://db:5432/speedquizdb
spring.flyway.user=speedquiz
spring.flyway.password=changeMe
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
# Additional Hibernate settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
