spring.application.name=BackendSpeed
spring.datasource.username=speedquiz
spring.datasource.postgresql.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.user=speedquiz
spring.flyway.password=${POSTGRES_PASSWORD}
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Suppress detailed Spring exception logging
logging.level.org.springframework.dao=info
logging.level.org.springframework.web=info

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
app.wanikani.use-dev-cache=true
