spring.datasource.postgresql.url=jdbc:postgresql://localhost:5432/speedquizdb
spring.flyway.url=jdbc:postgresql://localhost:5432/speedquizdb

# SQLite path doesn't need to be a real file for contextLoads
spring.datasource.sqlite.url=jdbc:sqlite::memory:
spring.datasource.sqlite.driverClassName=org.sqlite.JDBC

app.deck-import.path=./exampleHtmls