spring.datasource.postgresql.url=jdbc:postgresql://db:5432/speedquizdb
spring.datasource.postgresql.username=speedquiz
spring.datasource.postgresql.password=changeMe
spring.datasource.postgresql.driver-class-name=org.postgresql.Driver
spring.flyway.url=jdbc:postgresql://db:5432/speedquizdb

# SQLite for read-only Anki data extraction
spring.datasource.sqlite.url=jdbc:sqlite:/app/anki/collection.db
spring.datasource.sqlite.driverClassName=org.sqlite.JDBC
# Disable schema generation
spring.jpa.hibernate.ddl-auto=none
