# PostgreSQL
spring.datasource.postgresql.url=jdbc:postgresql://db:5432/speedquizdb
spring.datasource.postgresql.username=${SPRING_DATASOURCE_POSTGRESQL_USERNAME}
spring.datasource.postgresql.password=${SPRING_DATASOURCE_POSTGRESQL_PASSWORD}

# Flyway
spring.flyway.url=jdbc:postgresql://db:5432/speedquizdb
spring.flyway.username=${spring.datasource.postgresql.username}
spring.flyway.password=${spring.datasource.postgresql.password}

# SQLite (read-only Anki data)
spring.datasource.sqlite.url=jdbc:sqlite:/app/anki/collection.db
spring.datasource.sqlite.driverClassName=org.sqlite.JDBC

# App-specific overrides
app.deck-import.path=./htmlImports
