spring.datasource.postgresql.url=jdbc:postgresql://localhost:5432/speedquizdb
spring.flyway.url=jdbc:postgresql://localhost:5432/speedquizdb
spring.flyway.username=${spring.datasource.username}

spring.datasource.sqlite.url=jdbc:sqlite::memory:
spring.flyway.password=${spring.datasource.password}
spring.datasource.sqlite.driverClassName=org.sqlite.JDBC

app.deck-import.path=./exampleHtmls
# app.dictionary.required defaults to false ? app boots fine without the file in CI